[book]
title = "Eyad Salama"
authors = ["Eyad Salama"]
language = "en"

[output.html]
no-section-label = true
default-theme = "ayu"
additional-css = ["src/custom.css"]

[build]
build-dir = "book"
create-missing = false
use-default-preprocessors = true
extra-watch-dirs = []

[output.html.print]
enable = false    # include support for printable output
